# The MIT License (MIT)

# Copyright (c) 2019 Jimmy Herrera

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

FROM 184432115055.dkr.ecr.us-east-2.amazonaws.com/arruko/timeoff-base-test:latest
MAINTAINER Jimmy Herrera <jimmy@arruko.io>
LABEL application=timeoff

# Runtime args
ARG app_version
ARG node_env
ARG use_chrome
ARG port

# Application environment parameters
ENV APP_VERSION=${app_version}
ENV NODE_ENV ${node_env}
ENV USE_CHROME ${use_chrome}
ENV PORT ${port}

# Install app source code
WORKDIR /app/timeoff-management
COPY . .
RUN npm install

# Test app
CMD node bin/wwww > /dev/null 2>&1 &
CMD npm test