# -------------------------------------------------------------------
# CD Base Image
# TODO:
#   Install aws cli   
# --------------------------------------------------------------------
FROM python:2.7-alpine

RUN apk add --no-cache \
    nodejs npm 

ENV PATH $PATH:/usr/local/bin/
ENV PYTHON /usr/local/bin/

